import argparse
import json
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
from dominate import tags as html_tags
from dominate.util import raw as html_raw

def import_files():
    # this function will read in the generated files
    pass


def plot_abundance():
    # plots abundances of each taxa
    # include coloring based on good/bad bacteria
    pass


def plot_alpha_diversity():
    # plots a diversity metrics
    # includes an interpretation
    pass


def plot_PCA():
    # pca of patients in test-set
    # indicates indivisual patient run
    pass


def generate_report():
    # use json formating to export an html with the above plots.
    pass


def main():
    parser = argparse.ArgumentParser(description='BioTrack Report',
                                     prog='BioTrack_Report')

    parser.add_argument('-i',
                        '--input_file',
                        type=str,
                        help='Filename and path for table of patient data',
                        required=True)

    parser.add_argument('-p',
                        '--patient_id',
                        type=str,
                        help='Patient name or ID for report',
                        required=True)

    parser.add_argument('-r',
                        '--ref_data',
                        type=str,
                        help='Reference Data Generated by analysis.ipynb',
                        default='',
                        required=True)

    parser.add_argument('-o',
                        '--output_name',
                        type=str,
                        help='Add a custom filename for output (optional).',
                        default='',
                        required=False)

    args = parser.parse_args()

    # runs this file

    print(args.input_file)
    print(args.patient_id)
    print(args.ref_data)

    if args.output_name == '':
        print(args.patient_id+'.html')
    else:
        print(args.output_name+'.html')


if __name__ == '__main__':
    main()
